target("Core")
    set_kind("static")
    add_packages("glm")
    add_files("Core.mpp", {public = true})
    add_files("Core-math.mpp", {public = true})
    add_files("Core-ecs.mpp", {public = true})
    add_files("Core-system.mpp", {public = true})
